name: Docker Image Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Prepare Go
      uses: actions/setup-go@v2
      with:
        check-latest: true
    - name: Build
      run: go build ./cmd/updater/main.go
    
